#!/bin/sh

ELF_FILE=testProgram.elf
CIA_FILE=testProgram.cia

BANNERTOOL=./bannertool.exe
MAKEROM=./makerom.exe

APP_TITLE=execDebug
APP_DESCRIPTION=execDebug
APP_AUTHOR=guicrith
APP_PRODUCT_CODE=EXECDEBUG
APP_UNIQUE_ID=0xBAC00
APP_ICON=./default.png
APP_BANNER=./libretro_banner.png
APP_AUDIO=./silent.wav
APP_RSF=./template.rsf
APP_SYSTEM_MODE=64MB
APP_SYSTEM_MODE_EXT=124MB

MAKEROM_ARGS_COMMON="-rsf $APP_RSF -exefslogo -elf $ELF_FILE -icon $APP_TITLE.icn -banner $APP_TITLE.bnr -DAPP_TITLE=\"$APP_TITLE\" -DAPP_PRODUCT_CODE=\"$APP_PRODUCT_CODE\" -DAPP_UNIQUE_ID=$APP_UNIQUE_ID -DAPP_SYSTEM_MODE=$APP_SYSTEM_MODE -DAPP_SYSTEM_MODE_EXT=$APP_SYSTEM_MODE_EXT"

rm $APP_TITLE.icn $APP_TITLE.bnr

$BANNERTOOL makebanner -i "$APP_BANNER" -a "$APP_AUDIO" -o $APP_TITLE.bnr
$BANNERTOOL makesmdh -s "$APP_TITLE" -l "$APP_TITLE" -p "$APP_AUTHOR" -i $APP_ICON -o $APP_TITLE.icn
$MAKEROM -f cia -o $CIA_FILE $MAKEROM_ARGS_COMMON -DAPP_ENCRYPTED=false